### ISSUE TITLE
Telephony Channel closes the socket on a time out exception(15 seconds) from channel SDK 

### ISSUE THREAD

**Issue by PranemMSFT** [microsoft/botframework-telephony#102]
today if bot does NOT respond on a turn with in 15 seconds - Channel SDK throws timeoutException back to channel which causes the channel to terminate the websocket - causing bot to be not able to reply after 15 seconds.
can the socket not be closed even on exception so bot has a chance to reply and continue the conversation? (DLS channel today does NOT close the socket)

**Comment by arturl** [comment]
This is now fixed.
