### ISSUE TITLE
Some older documentation has outdated SSML names

### ISSUE THREAD

**Issue by goldenwitch** [microsoft/botframework-telephony#103]
https://github.com/microsoft/botframework-telephony/blob/main/ProcessSpeechInBotCode.md

Here we are using JessaNeural everywhere instead of the newer Aria.

Unrelatedly, this is the only place I could find where we are documenting how to get the callers phone number in the bot, and I think it's out of place.

**Comment by arturl** [comment]
Move out getting caller's phone number into a separate topic.

**Comment by arturl** [comment]
Fixed
