### ISSUE TITLE
Error once phone number has been binded in skype. Once initial call is made the bot does not pickup and say hello.

### ISSUE THREAD

**Issue by tgleigh202** [microsoft/botframework-telephony#20]
Replace:
await turnContext.SendActivityAsync(MessageFactory.Text("Hello and welcome!"), cancellationToken);
With
await turnContext.SendActivityAsync(MessageFactory.Text("Hello and welcome!", "Hello and welcome"), cancellationToken);
 
In summary the first parameter of MessageFactory.Text, indicates what text to write.  The second parameter indicates what text to speak.

**Comment by arturl** [comment]
Please reactivate if still active. Need a full repro.
