### ISSUE TITLE
DTMF input not sent to bot during barge in 

### ISSUE THREAD

**Issue by arturl** [microsoft/botframework-telephony#25]
**Repro**: Press a key on the telephone keypad (DTMF input) while the bot is playing out a message.
**Expected**: the bot stops playback and passes the DTMF signal to the bot. 
**Actual behavior**: is the playback is stopped but the bot does not receive the input.

From the customer:

> the behavior we are seeing is that a DTMF input interrupts the speech but the bot doesn’t process the input (in other words, the bot doesn’t seem to receive the input activity). If I press a valid DTMF key mid-prompt playback, I would expect the input to still be processed. Instead, the bot just goes silent until I again provide the input, which no user would know how to work with.

**Comment by hillnicole1107** [comment]
Issue resolved, does not repro after updates to barge in. DTMF tone is successfully reaching the bot for telephony test bot barge-in scenarios

**Comment by arturl** [comment]
Great, thank you @hillnicole1107
