### ISSUE TITLE
Unable to add Telephony Channel to the Bot Channel Registeration

### ISSUE THREAD

**Issue by rnpramasamy** [microsoft/botframework-telephony#27]
Hi.,

I am unable to add Telephony Channel to the Bot and I got below error:
![image](https://user-images.githubusercontent.com/5311453/100409112-2e4b2580-3091-11eb-94e2-430f4dbbe84d.png)

I had created new cognitive sevice and I didn't use communication service phone number to anyother bot.

**Comment by ovishesh** [comment]
Thanks @rnpramasamy for reporting this error. There are few different things that could be going wrong. Have to tried adding `+1` before your phone number?

If that does not work, please email us at ms-ivr-preview@microsoft.com to assist further. Thanks!

**Comment by arturl** [comment]
This should work now. If you still see this, let us know the error message. Thanks!

**Comment by gonzalorieto** [comment]
Hi! I'm getting the exact same error while configuring the `telephony channel` in my `web app bot`. 

One thing that I noticed is if I navigate to the ACS endpoint it says:
`<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0sCEkYAAAAADbKYeL6+ulQ7HFEW1tVTBUQlVFMzBFREdFMDIwNwBFZGdl`

Any ideas?
