### ISSUE TITLE
Sample for DTMF prompt

### ISSUE THREAD

**Issue by arturl** [microsoft/botframework-telephony#30]
Need a sample for SDK and Composer that demonstrates how to collect and aggregate DTMF input.

**Comment by kossrivastava** [comment]
The typical examples would be 'Enter your zipcode' or 'Enter the last 4 digits of your SSN'

**Comment by arturl** [comment]
@kossrivastava, here is an example I implemented, will this work for you? 
https://github.com/microsoft/botframework-telephony/tree/main/samples/csharp_dotnetcore/adaptive-dialog/01.number-prompt

**Comment by ovishesh** [comment]
Spoke to @kossrivastava offline. Good to close now.
