### ISSUE TITLE
Unable to save Telephony Channel to the Bot Channel Registeration

### ISSUE THREAD

**Issue by gonzalorieto** [microsoft/botframework-telephony#34]
Hi! I'm getting the exact same error as #27 while configuring the telephony channel in my web app bot.
![image](https://user-images.githubusercontent.com/72411352/107637449-e8900900-6c4c-11eb-85b1-59acbad87a8d.png)

One thing that I noticed is if I navigate to the ACS endpoint it says:
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0sCEkYAAAAADbKYeL6+ulQ7HFEW1tVTBUQlVFMzBFREdFMDIwNwBFZGdl

Any ideas?
Thanks!

**Comment by gonzalorieto** [comment]
Side note: used brand new phone number and cognitive service

**Comment by jrathor** [comment]
@kirankulkarni747 can you please take a look. Looks like an issue on BF portal side.
@gonzalorieto Can you share the botId/ bot handle?

**Comment by gonzalorieto** [comment]
Bot handle: `telephony-channel-bot`
Bot Id: `968f8c8a-7a38-418c-835e-2799b0e905c5`

I cant get another `toll-free` number since I deleted it trying go through all the steps, do you know why?

Thanks!

**Comment by kirankulkarni747** [comment]
@gonzalorieto based on our telemetry you are specifying a Cognitive service account that belongs to a region that's currently not supported by the Telephony channel. You will need to specify a Cognitive service account that belongs to either "eastus" or "westus2" region.

**Comment by gonzalorieto** [comment]
Oh! I set it to `westus`. Never saw the number `2` in the doc. Thanks!

Do you know anything about the `toll-free` numbers? Now I can't event choose it.

**Comment by gonzalorieto** [comment]
It worked just fine. Thanks. You can close this issue.
