### ISSUE TITLE
How Interrupt bot from playing a message

### ISSUE THREAD

**Issue by spedditi** [microsoft/botframework-telephony#35]
Is it possible to stop the bot from speaking if a caller talks over the bot. Get the input text and getting into next flow?

**Comment by arturl** [comment]
Hi @spedditi, we have limited support for barge-in (what you're asking for) in the preview release. Please see [here](https://github.com/microsoft/botframework-telephony/blob/main/experimental/TelephonyControl.md#allowdisable-barge-in)and let me know if it meets your immediate needs.

**Comment by ovishesh** [comment]
We have completed support for barge-in and is documented [here](https://github.com/microsoft/botframework-telephony/blob/main/BargeIn.md). Please reach back out as needed.
