### ISSUE TITLE
Update Portal UX with note about TC's current region availability 

### ISSUE THREAD

**Issue by ovishesh** [microsoft/botframework-telephony#38]
Update the Portal UX to include a note - "Telephony channel is currently supported in EastUS and WestUS2" with the filter

**Comment by arturl** [comment]
Already fixed @kirankulkarni747 ?

**Comment by kirankulkarni747** [comment]
It's fixed and is currently awaiting deployment.

**Comment by ovishesh** [comment]
Fixed and deployed to prod.
