### ISSUE TITLE
Usage example of batch DTMF

### ISSUE THREAD

**Issue by bojingo** [microsoft/botframework-telephony#46]
My team has hand-rolled support for multi-digit DTMF inputs for our telephony bot but have come to realize that this is a sore spot in terms of code maintainability. This is especially burdensome when we have parent/child dialogs and making sure that the `OnContinueDialogAsync` implementations don't interfere (sometimes we handle the DTMF input batching in the parent other times in the child - it got out of hand)

In this repo there is a [BatchDtmfAction](https://github.com/microsoft/botframework-telephony/blob/e81571deb729b35a0895c832e7499d6a047cfcf7/telephony-extensions/libraries/Microsoft.BotFramework.Composer.TelephonyCustomActions/Action/BatchDtmfAction.cs) but we are not sure how to utilize it. The only reference to this action is in [CustomActionComponentRegistration](https://github.com/microsoft/botframework-telephony/blob/e81571deb729b35a0895c832e7499d6a047cfcf7/telephony-extensions/libraries/Microsoft.BotFramework.Composer.TelephonyCustomActions/CustomActionComponentRegistration.cs), which I'm also not familiar with.

Is there a working usage example of this batch DTMF facility in action so that we can understand and potentially utilize it to improve our solution?

**Comment by arturl** [comment]
Telephony package now has the DTMF capabilities:
![image](https://user-images.githubusercontent.com/1875734/132584988-b17b6ecc-210f-4075-a759-db1dab325f2d.png)
