### ISSUE TITLE
NullReferenceException with empty activity received by the bot

### ISSUE THREAD

**Issue by arturl** [microsoft/botframework-telephony#58]
Don't have a consistent repro yet, but was reported by several users.

**Comment by p-nagpal** [comment]
The issue is alleviated by upgrading to SDK 4.12 and 4.13.preview. The Bot FX SDK team is also working on multiple fixes to avoid the issue altogether. Tracking issue: https://github.com/microsoft/botbuilder-dotnet/issues/5470

**Comment by arturl** [comment]
No repro
