### ISSUE TITLE
Enable quick telephony setup in portal by supporting creation of dependent resources from telephony blade

### ISSUE THREAD

**Issue by vanshu86** [microsoft/botframework-telephony#63]
Quick setup: Ideally it should be just 2 steps for creation of telephony bot-  create bot and then create telephony channel that does everything, the telephony UI should prompt to create ACS resource and Communication resource or reuse existing

**Comment by arturl** [comment]
Good suggestion.

**Comment by seaen** [comment]
A simple URL link to https://ms.portal.azure.com/#create/Microsoft.Communication ?

**Comment by ms-jb** [comment]
Resolved by adding a "Create new" link under each resource type.
