### ISSUE TITLE
Have an error on Telephony Channel page

### ISSUE THREAD

**Issue by AlDemTST** [microsoft/botframework-telephony#70]
I have a Telephone Channel with Communication Service and Speech Cognitive Service connected to it. I had to delete Speech Cognitive Service for the purpose to replace it and when I deleted Speech Service the error "The page cannot be displayed because an internal server error has occurred." appeared in Telephony Channel.

Step to reproduce
Delete Speech Cognitive Service which connected to the channel.

![screenshot](https://user-images.githubusercontent.com/65715811/115753448-e1e7e580-a3a3-11eb-8cf0-4281c23f7daa.png)

**Comment by jrathor** [comment]
Can you please share your botId?

**Comment by AlDemTST** [comment]
Hi @jrathor. Yes, I can.  "73c8c4f5-1995-4c77-aca0-e4e7b38b6512"

**Comment by jrathor** [comment]
I believe 73c8c4f5-1995-4c77-aca0-e4e7b38b6512 is appId of the bot. 
By botId, I meant bot handle as shown in the screenshot

![image](https://user-images.githubusercontent.com/61607553/115907946-66774a00-a41e-11eb-87ee-ea6b9a19fb42.png)

**Comment by AlDemTST** [comment]
This is bot handle "MOLChatBOT". Thank you for the screenshot.

**Comment by jrathor** [comment]
We are already working on permanent fix for this. For now I have mitigated the issue. Can you please try again?

**Comment by AlDemTST** [comment]
The error disappeared. Thank you.
