### ISSUE TITLE
Telephony transfer custom action doesn't work in Composer 2.0

### ISSUE THREAD

**Issue by dinobrago** [microsoft/botframework-telephony#87]
I have the samples 01 & 02 working in Composer 2.0

The 04.telephony-call-transfer sample doesn't work with Composer 2.0 presumably because of changes in the way custom actions are accessed. 

Do you have any procedure on how to access the custom actions in Composer 2.0?

**Comment by goldenwitch** [comment]
We are working on a composer 2.0 friendly version of this. I'll update here when it is released.

**Comment by arturl** [comment]
This is now solved.
