### ISSUE TITLE
Some Calling Numbers Only Include First 3 Digits of Phone Number 

### ISSUE THREAD

**Issue by alfenne** [microsoft/botframework-telephony#90]
We have a composer bot retrieving the calling phone number from the turn.activity.from.name memory scope. Our bot then takes this value on logs it to our telemetry data. In the past 7 days, this number has been correctly logged 7,274 times. However, there have been 34 occurrences where this value is only 3 digits.

![image](https://user-images.githubusercontent.com/64445981/126252057-a6ca4522-3016-4227-9df9-0e47780765b3.png)

Our bot has dependencies on services that rely on the phone number accurately being passed from the bot, causing lookup failures.

Example conversationIds:
ffd9ac82-47e7-4761-bb3f-2a11e1075681
a5236ec2-4870-4274-8a7c-f8670a0f1a76
b7399c8d-1ed9-4b3b-b76e-cefc48d7cace
86eca69e-7a39-4729-8b81-95beab84b2dc

**Comment by jaijitendra** [comment]
Partner SBC is sending 3-digit number as caller-id that is why TC is sending such phone number.

**Comment by alfenne** [comment]
Thank you for investigating! We will reach out to the partner SBC to notify them of this
