### ISSUE TITLE
08. Telephony - demo | breaking up at the start

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-telephony#97]
**Experienced behaviour**
_1st try._ 
Thank your for calling...
Sorry I didn't get that (hang up)
 
_2nd try_. 
Thank your for calling.
Are you calling…… (pause)
Sorry I didn’t' get that (hang up)

_3rd try_. 
Thank your for calling.
Are you calling option A and option B (etc) -> works

_4th/5th try_. 
Same happens as 2nd try: can't get past "are you calling..." then the bot apologizes and hangs up.

**Expected behaviour**
To consistently hear the greeting and options that follow, with no hang ups.

**Comment by arturl** [comment]
Hang up is now fixed, error handling works fine.
