### ISSUE TITLE
08. Telephony - demo | Experience suggestions 

### ISSUE THREAD

**Issue by Quirinevwm** [microsoft/botframework-telephony#98]
**Quick notes around expected behaviour**

- In the intro the bot calls out: "Are you calling to talk to (a=long name) or (b=long name), or press 0 for CS.
As a user you need to remember which departement from the start (the naming is contextual and hard to grasp), and there is no way to repeat the options now. Plus it's two options in 1 ask, if the options are short and crips that is easy to remember. 

- When bot call out: "Sorry I didn't get that". It's not asking the use to repeat or do anything - so it's not really helping and the bot hangs up. (potentially ask to repeat/try again - or hand over to CS)
 
- When I press a key (for example 1) the conversation automatically ends and the call hangs up. I'd expect the bot to continue talking and ignore the push when it's not relevant. 

- (tip most common asks, like "I don’t know/help/talk so someone" should route to CS)

**Comment by arturl** [comment]
Fixed by https://github.com/microsoft/botframework-telephony/pull/111
I did not change the long name but I fixed how the errors are handled, and the hangup issue.
